version: 2.0

jobs:
  build:
    docker:
      - image: ashishmathai/maven-alpine:0.1
        auth:
          username: ashishmathai
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn package
      - run: sudo target/*.war $CIRCLE_ARTIFACTS/
