version: 2.1

orbs:
  orbs:
    maven: circleci/maven@1.1
jobs:
  build:
    steps:
      - checkout
      - run: mkdir -p /tmp/artifacts
      - run: mv target/*.war /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/	  
