version: 2.0

orbs:
  orbs:
    maven: circleci/maven@1.1
workflows:
  maven_test:
    jobs:
      - maven/test
      - run: mkdir -p /tmp/artifacts
      - run: mv target/*.war /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/
